preferences:
  general:
    audioLib: PTB
    units: pix

window:
  # fullscr: True
  size: [3840, 2160]
  fullscr: False
  # size: [2000, 2000]
  # pos: [900, 80]
  color: [0, 0, 0]
  waitBlanking: True
  screen: 0

monitor:
  name: default
  width: 72     # in cm
  distance: 50  # in cm
  gamma: 1

mouse:
  visible: False

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_area_proportion: 0.4 0.5
    validation_area_proportion: 0.4 0.5
    calibration_type: HV9